# Generated by Django 3.1.5 on 2021-02-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gdfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.BigIntegerField()),
                ('MimeType', models.CharField(max_length=50)),
                ('ModTime', models.CharField(max_length=50, null=True)),
                ('IsDir', models.BooleanField(null=True)),
                ('gdid', models.CharField(max_length=50, null=True)),
                ('md5', models.CharField(max_length=50, null=True)),
                ('fsn', models.IntegerField()),
                ('dsn', models.IntegerField()),
                ('pdir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gdfiles', verbose_name='父目录')),
            ],
        ),
    ]
