# Generated by Django 3.1.5 on 2021-02-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdfiles',
            name='pdir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gdfiles', verbose_name='父目录'),
        ),
    ]
