# Generated by Django 3.1.5 on 2021-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210213_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdfiles',
            name='IsDir',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
