# Generated by Django 3.1.5 on 2021-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210213_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdfiles',
            name='dsn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gdfiles',
            name='fsn',
            field=models.IntegerField(default=0),
        ),
    ]
