# Generated by Django 3.1.5 on 2021-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210213_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdfiles',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='gdfiles',
            name='Path',
            field=models.CharField(max_length=200, verbose_name='完整路径'),
        ),
        migrations.AlterField(
            model_name='gdfiles',
            name='dsn',
            field=models.IntegerField(default=0, verbose_name='目录数'),
        ),
        migrations.AlterField(
            model_name='gdfiles',
            name='fsn',
            field=models.IntegerField(default=0, verbose_name='文件数'),
        ),
        migrations.AlterField(
            model_name='gdfiles',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
