# Generated by Django 3.1.5 on 2021-02-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210214_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdfiles',
            name='gdid',
        ),
    ]
